#!/usr/bin/env bash
set -e

working_dir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# prefer pip for installing python packages over the older easy_install
echo 'Check if pip is installed and updated'
if [[ -x `which pip` ]]; then
	pip install -U pip
else
    easy_install pip
fi

echo 'Check if ansible is installed and updated'
if [[ -x `which ansible` ]]; then
	pip install -U ansible
else
    pip install ansible
fi

echo 'Running Ansible to configure Dev machine'
ansible-playbook -K -i $working_dir/inventory $working_dir/playbook.yml